import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './components/header';
import { getData } from './utils/request';
import { useEffect } from 'react';
import { getAxiosData } from './utils/axios-request';

// export const dynamic = 'auto'
// export const dynamicParams = true
// export const revalidate = false
// export const fetchCache = 'force-cache';
// export const runtime = 'nodejs'
// export const preferredRegion = 'auto'
// export const maxDuration = 5

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const data = await getData();
  const data = await getAxiosData();
  console.log('**** data from layout', data.id);

  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <main className='flex flex-col items-center justify-between p-24'>
          {children}
        </main>
      </body>
    </html>
  );
}
