import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './components/header';
import { getData } from './utils/request';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await getData();
  console.log('**** data from layout', data.id);

  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <main className='flex flex-col items-center justify-between p-24'>
          {/* <pre>{data && JSON.stringify(data[0], null, 2)}</pre> */}
          {children}
        </main>
      </body>
    </html>
  );
}
